/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.com.gm.jdbc.mecatronics.interfaz;

import Datos.Cliente;
import Datos.Factura;
import Datos.mecatronicsService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaime
 */
public class PanelFactura extends javax.swing.JPanel {

    /**
     * Creates new form PanelCliente
     */
    DefaultTableModel modelo;
    public PanelFactura() {
        initComponents();
        popUpTable();
         ajustarImagenes.ajustarImagenPanel(labelSigno,"src/main/java/assets/imagenes/interrogacion.png");
         modelo=new DefaultTableModel();
         modelo.addColumn("id Factura");
          modelo.addColumn("Documento Cliente");
           modelo.addColumn("Nombre Cliente");
            modelo.addColumn("Apellido Cliente");
             modelo.addColumn("Motivo Factura");
              modelo.addColumn("Valor Factura");
               modelo.addColumn("Fecha Facturación");
                
         tabla.setModel(modelo);
                    
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        labelSigno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        panelActivo = new javax.swing.JPanel();
        labelActivo = new javax.swing.JLabel();
        panelInactivo = new javax.swing.JPanel();
        labelInactivo = new javax.swing.JLabel();
        panelAmbos = new javax.swing.JPanel();
        labelAmbos = new javax.swing.JLabel();
        panelBuscar = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelNuevoCliente = new javax.swing.JPanel();
        labelNuevoCliente = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(690, 700));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 700));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("FACTURAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 136, 29));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Email", "Telefono", "Pais", "Departamento", "Ciudad", "Barrio", "Direccion", "Plan", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 670, 170));

        labelSigno.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanel1.add(labelSigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 35, 35));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscador.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 45, 650, 43));

        panelActivo.setBackground(new java.awt.Color(255, 255, 255));
        panelActivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelActivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelActivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelActivo.setText("ACTIVO");
        labelActivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelActivoLayout = new javax.swing.GroupLayout(panelActivo);
        panelActivo.setLayout(panelActivoLayout);
        panelActivoLayout.setHorizontalGroup(
            panelActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelActivo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelActivoLayout.setVerticalGroup(
            panelActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(panelActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        panelInactivo.setBackground(new java.awt.Color(255, 255, 255));
        panelInactivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInactivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelInactivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInactivo.setText("INACTIVO");

        javax.swing.GroupLayout panelInactivoLayout = new javax.swing.GroupLayout(panelInactivo);
        panelInactivo.setLayout(panelInactivoLayout);
        panelInactivoLayout.setHorizontalGroup(
            panelInactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInactivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInactivoLayout.setVerticalGroup(
            panelInactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInactivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(panelInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 30));

        panelAmbos.setBackground(new java.awt.Color(255, 255, 255));
        panelAmbos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelAmbos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelAmbos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAmbos.setText("AMBOS");
        labelAmbos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelAmbosLayout = new javax.swing.GroupLayout(panelAmbos);
        panelAmbos.setLayout(panelAmbosLayout);
        panelAmbosLayout.setHorizontalGroup(
            panelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmbosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAmbos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAmbosLayout.setVerticalGroup(
            panelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAmbosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(panelAmbos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 30));

        panelBuscar.setBackground(new java.awt.Color(11, 73, 159));
        panelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));

        labelBuscar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel2.add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 670, 170));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, -1));

        panelNuevoCliente.setBackground(new java.awt.Color(11, 73, 159));
        panelNuevoCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));

        labelNuevoCliente.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        labelNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNuevoCliente.setText("Crear Facturación");
        labelNuevoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNuevoClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoClienteLayout = new javax.swing.GroupLayout(panelNuevoCliente);
        panelNuevoCliente.setLayout(panelNuevoClienteLayout);
        panelNuevoClienteLayout.setHorizontalGroup(
            panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        panelNuevoClienteLayout.setVerticalGroup(
            panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(panelNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 120, 30));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
       //  DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
      //  int a = tabla.getRowCount()-1;
       // for (int i = a; i >= 0; i--) {          
       // tb.removeRow(tb.getRowCount()-1);
       // }
     
        String []info=new String[7];
        //Cliente clienteAmostrar=mecatronicsService.leerClientePorDocumento(txtBuscador.getText());
        ArrayList<Factura> facturasAMostrar=mecatronicsService.leerFacturasPorDocumento(txtBuscador.getText());
         //System.out.println(facturasAMostrar.get(0).getFechaFacturacion());
       for(int i=0;i < facturasAMostrar.size();i++){
        info[0]= Integer.toString(facturasAMostrar.get(i).getIdFactura());
        info[1]=facturasAMostrar.get(i).getDocumentoCliente();
        info[2]=mecatronicsService.leerClientePorDocumento(facturasAMostrar.get(i).getDocumentoCliente()).getNombre();
        info[3]=mecatronicsService.leerClientePorDocumento(facturasAMostrar.get(i).getDocumentoCliente()).getApellido();
        info[4]=facturasAMostrar.get(i).getMotivoFactura();
        info[5]=String.valueOf(facturasAMostrar.get(i).getValorFactura());
        info[6]=facturasAMostrar.get(i).getFechaFacturacion();
       /* DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
		Date date =facturasAMostrar.get(i).getFechaFacturacion() ;        
		String dateToStr = dateFormat.format(date);
        
           */
        
        modelo.addRow(info);
        }
        
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void labelNuevoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoClienteMouseClicked
        try {
            PanelAgregarCliente p1 = new PanelAgregarCliente();
            
            Dashboard.cambiarPanel(p1);
        } catch (SQLException ex) {
            Logger.getLogger(PanelFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelNuevoClienteMouseClicked

    public static JTable getTabla() {
        return tabla;
    }

    public static void setTabla(JTable tabla) {
        PanelFactura.tabla = tabla;
    }

    
    public void popUpTable(){
    
        JPopupMenu popUpMenu= new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Borrar Cliente");
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mecatronicsService.borrarCliente();
                DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
        int a = tabla.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
            }
        });
        
        JMenuItem menuItem2 = new JMenuItem("Modificar Cliente");
        menuItem2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    PanelModificarCliente p1 = new PanelModificarCliente();
                    
                    Dashboard.cambiarPanel(p1);
                } catch (SQLException ex) {
                    Logger.getLogger(PanelFactura.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    popUpMenu.add(menuItem1);
    popUpMenu.add(menuItem2);
    tabla.setComponentPopupMenu(popUpMenu);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelActivo;
    private javax.swing.JLabel labelAmbos;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelInactivo;
    private javax.swing.JLabel labelNuevoCliente;
    private javax.swing.JLabel labelSigno;
    private javax.swing.JPanel panelActivo;
    private javax.swing.JPanel panelAmbos;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelInactivo;
    private javax.swing.JPanel panelNuevoCliente;
    public static javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
