/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.com.gm.jdbc.mecatronics.interfaz;

import Datos.MecatronicsDAO;

/**
 *
 * @author Jaime
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        labelNombre.setText(MecatronicsDAO.empleadoActual.getNombre());
        labelApellido.setText(MecatronicsDAO.empleadoActual.getApellido());
        labelCargo.setText(MecatronicsDAO.empleadoActual.getCargo());
         ajustarImagenes.ajustarImagenPanel(labelFoto, MecatronicsDAO.empleadoActual.getRutaImagen());
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        separadorNombre = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        separadorApellido = new javax.swing.JSeparator();
        separadorApellido1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(690, 420));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        labelNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelNombre.setText("jLabel2");
        labelNombre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, 30));

        separadorNombre.setBackground(new java.awt.Color(204, 204, 204));
        separadorNombre.setForeground(new java.awt.Color(0, 0, 0));
        separadorNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        separadorNombre.setMinimumSize(new java.awt.Dimension(50, 20));
        separadorNombre.setOpaque(true);
        separadorNombre.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, 1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        labelApellido.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelApellido.setText("jLabel2");
        labelApellido.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 30));

        separadorApellido.setBackground(new java.awt.Color(204, 204, 204));
        separadorApellido.setForeground(new java.awt.Color(0, 0, 0));
        separadorApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        separadorApellido.setMinimumSize(new java.awt.Dimension(50, 20));
        separadorApellido.setOpaque(true);
        separadorApellido.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 1));

        separadorApellido1.setBackground(new java.awt.Color(204, 204, 204));
        separadorApellido1.setForeground(new java.awt.Color(0, 0, 0));
        separadorApellido1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        separadorApellido1.setMinimumSize(new java.awt.Dimension(50, 20));
        separadorApellido1.setOpaque(true);
        separadorApellido1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, 1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Cargo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        labelCargo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelCargo.setText("jLabel2");
        labelCargo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 210, 30));

        labelFoto.setText("FOTO");
        labelFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 90, 171), 2, true));
        labelFoto.setPreferredSize(new java.awt.Dimension(170, 150));
        jPanel1.add(labelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JSeparator separadorApellido;
    private javax.swing.JSeparator separadorApellido1;
    private javax.swing.JSeparator separadorNombre;
    // End of variables declaration//GEN-END:variables
}
